import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

export async function createEpisodes() {
  const episodesToCreate = [
    //Nier
    {
      id: 1,
      name: 'Ou não ser 2B E-1',
      url: 'https://do0od.com/e/hgdceen7xj83',
      episodeOrder: 1,
      seasonId: 4,
    },
    {
      id: 2,
      name: 'Escapando da cidade E-2',
      url: 'https://do0od.com/e/tahwsqbhfkl1',
      episodeOrder: 2,
      seasonId: 4,
    },
    {
      id: 3,
      name: 'Tempo de descanso E-3',
      url: 'https://do0od.com/e/2u0crgtlg545',
      episodeOrder: 3,
      seasonId: 4,
    },
    {
      id: 4,
      name: 'Montanha alta E-4',
      url: 'https://do0od.com/e/23oe4z02kkqs',
      episodeOrder: 4,
      seasonId: 4,
    },
    {
      id: 5,
      name: 'Desvairado E-5',
      url: 'https://do0od.com/e/oi4z2k8o31sk',
      episodeOrder: 5,
      seasonId: 4,
    },
    {
      id: 6,
      name: 'Loba solitária E-6',
      url: 'https://do0od.com/e/211lfvsl0025',
      episodeOrder: 6,
      seasonId: 4,
    },
    {
      id: 7,
      name: 'Ações questionáveis E-7',
      url: 'https://do0od.com/e/hh3ieeai7h34',
      episodeOrder: 7,
      seasonId: 4,
    },
    {
      id: 8,
      name: 'Aji wo Kutta? E-8',
      url: 'https://do0od.com/e/1xhqw9pj0oti',
      episodeOrder: 8,
      seasonId: 4,
    },
    {
      id: 9,
      name: 'Gula por conhecimento E-9',
      url: 'https://do0od.com/e/kgha7qwjlzf0',
      episodeOrder: 9,
      seasonId: 4,
    },
    {
      id: 10,
      name: 'Excesso de zelo E-10',
      url: 'https://do0od.com/e/du6je0e4ueng',
      episodeOrder: 10,
      seasonId: 4,
    },
    {
      id: 11,
      name: 'Batalha inebriante E-11',
      url: 'https://do0od.com/e/4h6mcsl55t5n',
      episodeOrder: 11,
      seasonId: 4,
    },
    {
      id: 12,
      name: 'Flores para máquinas E-12',
      url: 'https://do0od.com/e/z252d1bauziq',
      episodeOrder: 12,
      seasonId: 4,
    },
    //Mashle
    {
      id: 13,
      name: 'Músculos trabalhados E-1',
      url: 'https://do0od.com/e/7m4ex93ksdi5',
      episodeOrder: 1,
      seasonId: 3,
    },
    {
      id: 14,
      name: 'Labirinto esquisito E-2',
      url: 'https://do0od.com/e/3966knhivkg6',
      episodeOrder: 2,
      seasonId: 3,
    },
    {
      id: 15,
      name: 'É melhor não irritar E-3',
      url: 'https://do0od.com/e/mepscnbfxtjk',
      episodeOrder: 3,
      seasonId: 3,
    },
    {
      id: 16,
      name: 'O mago forte E-4',
      url: 'https://do0od.com/e/mtyay0h99va1',
      episodeOrder: 4,
      seasonId: 3,
    },
    {
      id: 17,
      name: 'O colega desprezado E-5',
      url: 'https://doodstream.com/e/6bpn5045kyhk',
      episodeOrder: 5,
      seasonId: 3,
    },
    {
      id: 18,
      name: 'O mago de ferro E-6',
      url: 'https://do0od.com/e/r18iflsbyqhj',
      episodeOrder: 6,
      seasonId: 3,
    },
    {
      id: 19,
      name: 'Carta misteriosa E-6.5',
      url: 'https://do0od.com/e/ppzi57n7e3g6',
      episodeOrder: 7,
      seasonId: 3,
    },
    {
      id: 20,
      name: 'Mago marionetista E-7',
      url: 'https://do0od.com/e/8b9orpoebej3',
      episodeOrder: 8,
      seasonId: 3,
    },
    {
      id: 21,
      name: 'Magos lobos E-8',
      url: 'https://do0od.com/e/ra5nxdn9o4qr',
      episodeOrder: 9,
      seasonId: 3,
    },
    {
      id: 22,
      name: 'Mago da aceleração E-9',
      url: 'https://do0od.com/e/36u36zi2h534',
      episodeOrder: 10,
      seasonId: 3,
    },
    {
      id: 23,
      name: 'Visionário divino E-10',
      url: 'https://do0od.com/e/fgmd4dqqnhlj',
      episodeOrder: 11,
      seasonId: 3,
    },
    {
      id: 24,
      name: 'Lei do mais forte E-11',
      url: 'https://do0od.com/e/9izc2kmpshem',
      episodeOrder: 12,
      seasonId: 3,
    },
    {
      id: 25,
      name: 'O espelho mágico E-12',
      url: 'https://do0od.com/e/r3v4og3ehx4a',
      episodeOrder: 13,
      seasonId: 3,
    },
    {
      id: 26,
      name: 'Os visionários E-13',
      url: 'https://do0od.com/e/y01rs4v3awlu',
      episodeOrder: 14,
      seasonId: 3,
    },
    {
      id: 27,
      name: 'A terra natal E-14',
      url: 'https://do0od.com/e/cig2npe5gvix',
      episodeOrder: 15,
      seasonId: 3,
    },
    //Spy x Family
    {
      id: 28,
      name: 'Operação Strix E-1',
      url: 'https://do0od.com/e/g3oj50jxe5ju',
      episodeOrder: 1,
      seasonId: 5,
    },
    {
      id: 29,
      name: 'Garantir uma esposa E-2',
      url: 'https://do0od.com/e/buaxpyi7zo1c',
      episodeOrder: 2,
      seasonId: 5,
    },
    {
      id: 30,
      name: 'Preparativos E-3',
      url: 'https://do0od.com/e/jxb9cxymxyjc',
      episodeOrder: 3,
      seasonId: 5,
    },
    {
      id: 31,
      name: 'A entrevista E-4',
      url: 'https://do0od.com/e/gu4r9bz1g9iz',
      episodeOrder: 4,
      seasonId: 5,
    },
    {
      id: 32,
      name: 'Aprovados ou reprovados E-5',
      url: 'https://do0od.com/e/yehmv4a4irh3',
      episodeOrder: 5,
      seasonId: 5,
    },
    {
      id: 33,
      name: 'Esquema de amizade E-6',
      url: 'https://do0od.com/e/wa3zazqb6rhh',
      episodeOrder: 6,
      seasonId: 5,
    },
    {
      id: 34,
      name: 'Segundo filho do alvo E-7',
      url: 'https://do0od.com/e/wa3zazqb6rhh',
      episodeOrder: 7,
      seasonId: 5,
    },
    {
      id: 35,
      name: 'Camuflagem E-8',
      url: 'https://do0od.com/e/ttjfqptxnufk',
      episodeOrder: 8,
      seasonId: 5,
    },
    {
      id: 36,
      name: 'Ostente o seu amor E-9',
      url: 'https://do0od.com/e/jargh53ohio7',
      episodeOrder: 9,
      seasonId: 5,
    },
    {
      id: 37,
      name: 'O grande plano E-10',
      url: 'https://do0od.com/e/rzdc4wueac85',
      episodeOrder: 10,
      seasonId: 5,
    },
    {
      id: 38,
      name: 'Estrela E-11',
      url: 'https://do0od.com/e/cmggkpn2hxkz',
      episodeOrder: 11,
      seasonId: 5,
    },
    {
      id: 39,
      name: 'Parque dos pinguins E-12',
      url: 'https://do0od.com/e/gbhlctthl3ot',
      episodeOrder: 12,
      seasonId: 5,
    },
    //overlord
    {
      id: 40,
      name: 'Fim e começo E-1',
      url: 'https://do0od.com/e/cmsnkf9f4hok',
      episodeOrder: 1,
      seasonId: 6,
    },
    {
      id: 41,
      name: 'Guardiões E-2',
      url: 'https://do0od.com/e/cof7ecfn9wic',
      episodeOrder: 2,
      seasonId: 6,
    },
    {
      id: 42,
      name: 'Batalha na vila E-3',
      url: 'https://do0od.com/e/mtew35vvqihs',
      episodeOrder: 3,
      seasonId: 6,
    },
    {
      id: 43,
      name: 'Senhor da morte E-4',
      url: 'https://do0od.com/e/jqdjup44s8sp',
      episodeOrder: 4,
      seasonId: 6,
    },
    {
      id: 44,
      name: 'Dois aventureiros E-5',
      url: 'https://do0od.com/e/bjjcqeexf6xe',
      episodeOrder: 5,
      seasonId: 6,
    },
    {
      id: 45,
      name: 'Jornada E-6',
      url: 'https://do0od.com/e/56xqolkmbsmi',
      episodeOrder: 6,
      seasonId: 6,
    },
    {
      id: 46,
      name: 'Rei sábio E-7',
      url: 'https://do0od.com/e/c6ns2cqft4f0',
      episodeOrder: 7,
      seasonId: 6,
    },
    {
      id: 47,
      name: 'Espadas duplas E-8',
      url: 'https://do0od.com/e/fawclmn3b3ej',
      episodeOrder: 8,
      seasonId: 6,
    },
    {
      id: 48,
      name: 'O cavaleiro negro E-9',
      url: 'https://do0od.com/e/kp84hd7sg7of',
      episodeOrder: 9,
      seasonId: 6,
    },
    {
      id: 49,
      name: 'Vampiro verdadeiro E-10',
      url: 'https://do0od.com/e/buxoe9frhuf5',
      episodeOrder: 10,
      seasonId: 6,
    },
    {
      id: 50,
      name: 'Confusão E-11',
      url: 'https://do0od.com/e/30j4g0wxhwjs',
      episodeOrder: 11,
      seasonId: 6,
    },
    {
      id: 51,
      name: 'A valquíria E-12',
      url: 'https://do0od.com/e/tqairvb6vep8',
      episodeOrder: 12,
      seasonId: 6,
    },
    {
      id: 52,
      name: 'Jogador vs NPC E-13',
      url: 'https://do0od.com/e/8sv9eps6uclt',
      episodeOrder: 13,
      seasonId: 6,
    },
    {
      id: 53,
      name: 'A alvorada E-1',
      url: 'https://do0od.com/e/xd07znxu395w',
      episodeOrder: 1,
      seasonId: 7,
    },
    {
      id: 54,
      name: 'Despedida E-2',
      url: 'https://do0od.com/e/mjw6nrcecz9s',
      episodeOrder: 2,
      seasonId: 7,
    },
    {
      id: 55,
      name: 'Lizardmen E-3',
      url: 'https://do0od.com/e/hkewzt35auas',
      episodeOrder: 3,
      seasonId: 7,
    },
    {
      id: 56,
      name: 'Exército da morte E-4',
      url: 'https://do0od.com/e/e9fgf0p25nb3',
      episodeOrder: 4,
      seasonId: 7,
    },
    {
      id: 57,
      name: 'O deus congelante E-5',
      url: 'https://do0od.com/e/v7e88ptt35ow',
      episodeOrder: 5,
      seasonId: 7,
    },
    {
      id: 58,
      name: 'Os que auxiliam E-6',
      url: 'https://do0od.com/e/8l4w8gi7wpm4',
      episodeOrder: 6,
      seasonId: 7,
    },
    {
      id: 59,
      name: 'Rosas Azuis E-7',
      url: 'https://do0od.com/e/vbrrwrqoy3i1',
      episodeOrder: 7,
      seasonId: 7,
    },
    {
      id: 60,
      name: 'O sentimento E-8',
      url: 'https://do0od.com/e/w13roh5mk1sw',
      episodeOrder: 8,
      seasonId: 7,
    },
    {
      id: 61,
      name: 'Faíscas E-9',
      url: 'https://do0od.com/e/i9dhdy9h4loo',
      episodeOrder: 9,
      seasonId: 7,
    },
    {
      id: 62,
      name: 'Distúrbios E-10',
      url: 'https://do0od.com/e/gk3sxqle11o2',
      episodeOrder: 10,
      seasonId: 7,
    },
    {
      id: 63,
      name: 'Jaldabaoth E-11',
      url: 'https://do0od.com/e/kvwjxnls29at',
      episodeOrder: 11,
      seasonId: 7,
    },
    {
      id: 64,
      name: 'A batalha final E-12',
      url: 'https://do0od.com/e/pthrk8xgi4j1',
      episodeOrder: 12,
      seasonId: 7,
    },
    {
      id: 65,
      name: 'O trunfo final E-13',
      url: 'https://do0od.com/e/gth9280tjyz8',
      episodeOrder: 13,
      seasonId: 7,
    },
    //Jujutsu
    {
      id: 66,
      name: 'Ryomen sukuna E-1',
      url: 'https://do0od.com/e/bbgbnop08rr4',
      episodeOrder: 1,
      seasonId: 1,
    },
    {
      id: 67,
      name: 'Por mim mesmo E-2',
      url: 'https://do0od.com/e/tur015yan50j',
      episodeOrder: 2,
      seasonId: 1,
    },
    {
      id: 68,
      name: 'Garota de aço E-3',
      url: 'https://do0od.com/e/iph8c0jkw104',
      episodeOrder: 3,
      seasonId: 1,
    },
    {
      id: 69,
      name: 'Morte ao feto E-4',
      url: 'https://do0od.com/e/vqjnm4c63jkm',
      episodeOrder: 4,
      seasonId: 1,
    },
    {
      id: 70,
      name: 'Amaldiçoado E-5',
      url: 'https://do0od.com/e/4wnpetd3jgcp',
      episodeOrder: 5,
      seasonId: 1,
    },
    {
      id: 71,
      name: 'Depois da chuva E-6',
      url: 'https://do0od.com/e/hgbx3gqvix4c',
      episodeOrder: 6,
      seasonId: 1,
    },
    {
      id: 72,
      name: 'Ataque E-7',
      url: 'https://do0od.com/e/o3cz5t8naoep',
      episodeOrder: 7,
      seasonId: 1,
    },
    {
      id: 73,
      name: 'Tédio E-8',
      url: 'https://do0od.com/e/jrg79j4luqhq',
      episodeOrder: 8,
      seasonId: 1,
    },
    {
      id: 74,
      name: 'Peixes pequenos E-9',
      url: 'https://do0od.com/e/ar2mdprzogw2',
      episodeOrder: 9,
      seasonId: 1,
    },
    {
      id: 75,
      name: 'Transfiguração E-10',
      url: 'https://do0od.com/e/6h9z2kwjx282',
      episodeOrder: 10,
      seasonId: 1,
    },
    {
      id: 76,
      name: 'Mente fechada E-11',
      url: 'https://do0od.com/e/kj5dyl1a4whe',
      episodeOrder: 11,
      seasonId: 1,
    },
    {
      id: 77,
      name: 'Para você E-12',
      url: 'https://do0od.com/e/n80h80kpugoz',
      episodeOrder: 12,
      seasonId: 1,
    },
    {
      id: 78,
      name: 'Amanhã E-13',
      url: 'https://do0od.com/e/cwx37dpgeopo',
      episodeOrder: 13,
      seasonId: 1,
    },
    {
      id: 79,
      name: 'Intercâmbio 0 E-14',
      url: 'https://do0od.com/e/1xqbziuv7h70',
      episodeOrder: 14,
      seasonId: 1,
    },
    {
      id: 80,
      name: 'Intercâmbio 1 E-15',
      url: 'https://do0od.com/e/j70lroewijc2',
      episodeOrder: 15,
      seasonId: 1,
    },
    {
      id: 81,
      name: 'Intercâmbio 2 E-16',
      url: 'https://do0od.com/e/jrrepajwktru',
      episodeOrder: 16,
      seasonId: 1,
    },
    {
      id: 82,
      name: 'Intercâmbio 3 E-17',
      url: 'https://do0od.com/e/lwdolcfyquwc',
      episodeOrder: 17,
      seasonId: 1,
    },
    {
      id: 83,
      name: 'Sábio E-18',
      url: 'https://do0od.com/e/bq9tjvs1pixb',
      episodeOrder: 18,
      seasonId: 1,
    },
    {
      id: 84,
      name: 'Fulgor negro E-19',
      url: 'https://do0od.com/e/7vwl50nurwux',
      episodeOrder: 19,
      seasonId: 1,
    },
    {
      id: 85,
      name: 'Fora do padrão E-20',
      url: 'https://do0od.com/e/9celqs8acell',
      episodeOrder: 20,
      seasonId: 1,
    },
    {
      id: 86,
      name: 'Jujutsu koshien E-21',
      url: 'https://do0od.com/e/1g8h3n4gpiyn',
      episodeOrder: 21,
      seasonId: 1,
    },
    {
      id: 87,
      name: 'A origem 1 E-22',
      url: 'https://do0od.com/e/zj6x6nwasbbo',
      episodeOrder: 22,
      seasonId: 1,
    },
    {
      id: 88,
      name: 'A origem 2 E-23',
      url: 'https://do0od.com/e/yn8acoc3zlfs',
      episodeOrder: 23,
      seasonId: 1,
    },
    {
      id: 89,
      name: 'Cúmplices E-24',
      url: 'https://do0od.com/e/1iresidzf93v',
      episodeOrder: 24,
      seasonId: 1,
    },
    {
      id: 90,
      name: 'Inventário E-1',
      url: 'https://do0od.com/e/2t3b30riuhl7',
      episodeOrder: 1,
      seasonId: 2,
    },
    {
      id: 91,
      name: 'Inventário 2 E-2',
      url: 'https://do0od.com/e/l31a1k6nzow0',
      episodeOrder: 2,
      seasonId: 2,
    },
    {
      id: 92,
      name: 'Inventário 3 E-3',
      url: 'https://do0od.com/e/5blymeibuo0y',
      episodeOrder: 3,
      seasonId: 2,
    },
    {
      id: 93,
      name: 'Inventário 4 E-4',
      url: 'https://do0od.com/e/2nf9crsvt181',
      episodeOrder: 4,
      seasonId: 2,
    },
    {
      id: 94,
      name: 'Morte prematura E-5',
      url: 'https://do0od.com/e/qq8zsxtwir48',
      episodeOrder: 5,
      seasonId: 2,
    },
    {
      id: 95,
      name: 'E é assim E-6',
      url: 'https://do0od.com/e/f23srzqevreg',
      episodeOrder: 6,
      seasonId: 2,
    },
    {
      id: 96,
      name: 'Festival ao fim E-7',
      url: 'https://do0od.com/e/1ifg8yfgkpej',
      episodeOrder: 7,
      seasonId: 2,
    },
    {
      id: 97,
      name: 'Incidente E-8',
      url: 'https://do0od.com/e/ilr9uvb0yfjo',
      episodeOrder: 8,
      seasonId: 2,
    },
    {
      id: 98,
      name: 'Incidente 2 E-9',
      url: 'https://do0od.com/e/bwzqgv0wc1iy',
      episodeOrder: 9,
      seasonId: 2,
    },
    {
      id: 99,
      name: 'Pandemônio E-10',
      url: 'https://do0od.com/e/vw7eocidi4av',
      episodeOrder: 10,
      seasonId: 2,
    },
    {
      id: 100,
      name: 'Sessão E-11',
      url: 'https://do0od.com/e/vgyq5qosedxh',
      episodeOrder: 11,
      seasonId: 2,
    },
    {
      id: 101,
      name: 'Faca cega E-12',
      url: 'https://do0od.com/e/ozxjsiqul54j',
      episodeOrder: 12,
      seasonId: 2,
    },
    {
      id: 102,
      name: 'Escama E-13',
      url: 'https://do0od.com/e/vc8q6xaxxq4y',
      episodeOrder: 13,
      seasonId: 2,
    },
    {
      id: 103,
      name: 'Flutuações E-14',
      url: 'https://do0od.com/e/2ri1791a6roh',
      episodeOrder: 14,
      seasonId: 2,
    },
    {
      id: 104,
      name: 'Flutuações 2 E-15',
      url: 'https://do0od.com/e/ti9pgbbo46xj',
      episodeOrder: 15,
      seasonId: 2,
    },
    {
      id: 105,
      name: 'Trovão E-16',
      url: 'https://do0od.com/e/ri421rt3n034',
      episodeOrder: 16,
      seasonId: 2,
    },
    {
      id: 106,
      name: 'Trovão 2 E-17',
      url: 'https://do0od.com/e/o6stm0minc0q',
      episodeOrder: 17,
      seasonId: 2,
    },
    {
      id: 107,
      name: 'Certo e errado E-18',
      url: 'https://do0od.com/e/3qoi56wa8g90',
      episodeOrder: 18,
      seasonId: 2,
    },
    {
      id: 108,
      name: 'Certo e errado 2 E-19',
      url: 'https://do0od.com/e/spgo928ntd28',
      episodeOrder: 19,
      seasonId: 2,
    },
    {
      id: 109,
      name: 'Certo e errado 3 E-20',
      url: 'https://do0od.com/e/1v0q15oa8x6l',
      episodeOrder: 20,
      seasonId: 2,
    },
    {
      id: 110,
      name: 'Metamorfose E-21',
      url: 'https://do0od.com/e/t3h1rkiid75o',
      episodeOrder: 21,
      seasonId: 2,
    },
    {
      id: 111,
      name: 'Metamorfose 2 E-22',
      url: 'https://do0od.com/e/t7mwg8ss0zvh',
      episodeOrder: 22,
      seasonId: 2,
    },
    {
      id: 112,
      name: 'Portões fechado E-23',
      url: 'https://do0od.com/e/824h79zkihmy',
      episodeOrder: 23,
      seasonId: 2,
    },
    {
      id: 113,
      name: 'Cachorro e Moto E-1',
      url: 'https://do0od.com/e/tslwc42nizbj',
      episodeOrder: 1,
      seasonId: 9,
    },
    {
      id: 114,
      name: 'Chegada em Tokyo E-2',
      url: 'https://do0od.com/e/bzjtui5whoyk',
      episodeOrder: 2,
      seasonId: 9,
    },
    {
      id: 115,
      name: 'O paradeiro E-3',
      url: 'https://do0od.com/e/07jdf1swaae9',
      episodeOrder: 3,
      seasonId: 9,
    },
    {
      id: 116,
      name: 'Resgate E-4',
      url: 'https://do0od.com/e/ymh4ibcvuorw',
      episodeOrder: 4,
      seasonId: 9,
    },
    {
      id: 117,
      name: 'O demônio da arma E-5',
      url: 'https://do0od.com/e/0mxxo68hg6m7',
      episodeOrder: 5,
      seasonId: 9,
    },
    {
      id: 118,
      name: 'Matem o Denji E-6',
      url: 'https://do0od.com/e/mi11lyp3fxeb',
      episodeOrder: 6,
      seasonId: 9,
    },
    {
      id: 119,
      name: 'O sabor do beijo E-7',
      url: 'https://do0od.com/e/qc4rbglsn2nk',
      episodeOrder: 7,
      seasonId: 9,
    },
    {
      id: 120,
      name: 'O som do disparo E-8',
      url: 'https://do0od.com/e/oatx0t0qft2e',
      episodeOrder: 8,
      seasonId: 9,
    },
    {
      id: 121,
      name: 'De Kyoto E-9',
      url: 'https://do0od.com/e/nr6uw9eai1fv',
      episodeOrder: 9,
      seasonId: 9,
    },
    {
      id: 122,
      name: 'Ainda mais pobre E-10',
      url: 'https://do0od.com/e/otoxh5vkvur4',
      episodeOrder: 10,
      seasonId: 9,
    },
    {
      id: 123,
      name: 'Início do plano E-11',
      url: 'https://do0od.com/e/9xt5s9jz7b5v',
      episodeOrder: 11,
      seasonId: 9,
    },
    {
      id: 124,
      name: 'Katana vs Moto E-12',
      url: 'https://do0od.com/e/lif88ftcpw2q',
      episodeOrder: 12,
      seasonId: 9,
    },
  ];

  for (const episodesData of episodesToCreate) {
    const existingSeason = await prisma.seasons.findUnique({
      where: { id: episodesData.seasonId },
    });

    const existingEpisodes = await prisma.episodes.findMany({
      where: { name: episodesData.name },
    });

    if (existingSeason) {
      if (existingEpisodes.length === 0) {
        await prisma.episodes.create({
          data: {
            name: episodesData.name,
            url: episodesData.url,
            episodeOrder: episodesData.episodeOrder,
            seasons: {
              connect: {
                id: episodesData.seasonId,
              },
            },
          },
        });
      }
    }
  }
}

createEpisodes()
  .then(() => {
    console.log('Episódios gerados com sucesso.');
  })
  .catch((error) => {
    console.error('Erro ao gerar os episódios:', error);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
