import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

export async function createEpisodes() {
  const episodesToCreate = [
    //Nier
    {
      id: 1,
      name: 'Ou não ser 2B E-1',
      url: 'https://do0od.com/e/hgdceen7xj83',
      thumbnailUrl: 'https://img.doodcdn.co/cover/5hv76vtapgc01dl1-pqcvwc8xp2s3.jpg',
      episodeOrder: 1,
      seasonId: 4,
    },
    {
      id: 2,
      name: 'Escapando E-2',
      url: 'https://do0od.com/e/tahwsqbhfkl1',
      thumbnailUrl: 'https://img.doodcdn.co/cover/sgn0luram9u6vl9g-dxd2zbdej6ds.jpg',
      episodeOrder: 2,
      seasonId: 4,
    },
    {
      id: 3,
      name: 'Descanso E-3',
      url: 'https://do0od.com/e/2u0crgtlg545',
      thumbnailUrl: 'https://img.doodcdn.co/snaps/oqgb7ypuk0etkc64.jpg',
      episodeOrder: 3,
      seasonId: 4,
    },
    {
      id: 4,
      name: 'Montanha alta E-4',
      url: 'https://do0od.com/e/23oe4z02kkqs',
      thumbnailUrl: 'https://img.doodcdn.co/snaps/m6psg7sygd6n0863.jpg',
      episodeOrder: 4,
      seasonId: 4,
    },
    {
      id: 5,
      name: 'Desvairado E-5',
      url: 'https://do0od.com/e/oi4z2k8o31sk',
      thumbnailUrl: 'https://img.doodcdn.co/snaps/prsirl0oj1aqb5c3.jpg',
      episodeOrder: 5,
      seasonId: 4,
    },
    {
      id: 6,
      name: 'Loba solitária E-6',
      url: 'https://do0od.com/e/211lfvsl0025',
      thumbnailUrl: 'https://img.doodcdn.co/snaps/8qrwvz3j9ol9rvuf.jpg',
      episodeOrder: 6,
      seasonId: 4,
    },
    {
      id: 7,
      name: 'Questionáveis E-7',
      url: 'https://do0od.com/e/hh3ieeai7h34',
      thumbnailUrl: 'https://img.doodcdn.co/snaps/c317jl2orius034z.jpg',
      episodeOrder: 7,
      seasonId: 4,
    },
    {
      id: 8,
      name: 'Aji wo Kutta? E-8',
      url: 'https://do0od.com/e/1xhqw9pj0oti',
      thumbnailUrl: 'https://img.doodcdn.co/snaps/slrtug22qks2yy1c.jpg',
      episodeOrder: 8,
      seasonId: 4,
    },
    {
      id: 9,
      name: 'Conhecimento E-9',
      url: 'https://do0od.com/e/kgha7qwjlzf0',
      thumbnailUrl: 'https://img.doodcdn.co/snaps/m8369pkhwe7gj555.jpg',
      episodeOrder: 9,
      seasonId: 4,
    },
    {
      id: 10,
      name: 'Excesso de zelo E-10',
      url: 'https://do0od.com/e/du6je0e4ueng',
      thumbnailUrl: 'https://img.doodcdn.co/snaps/5j36zfm0m3omzomn.jpg',
      episodeOrder: 10,
      seasonId: 4,
    },
    {
      id: 11,
      name: 'Batalha inebriante E-11',
      url: 'https://do0od.com/e/4h6mcsl55t5n',
      thumbnailUrl: 'https://img.doodcdn.co/snaps/h4i8ysj4ic5ku0df.jpg',
      episodeOrder: 11,
      seasonId: 4,
    },
    {
      id: 12,
      name: 'Flores e máquinas E-12',
      url: 'https://do0od.com/e/z252d1bauziq',
      thumbnailUrl: 'https://img.doodcdn.co/snaps/cs3xf6kkbmk915su.jpg',
      episodeOrder: 12,
      seasonId: 4,
    },
    //Mashle
    {
      id: 13,
      name: 'Músculos trabalhados E-1',
      url: 'https://do0od.com/e/7m4ex93ksdi5',
      thumbnailUrl: 'https://img.doodcdn.co/snaps/w6s3zd3o969cise8.jpg',
      episodeOrder: 1,
      seasonId: 3,
    },
    {
      id: 14,
      name: 'Labirinto esquisito E-2',
      url: 'https://do0od.com/e/3966knhivkg6',
      thumbnailUrl: 'https://img.doodcdn.co/snaps/865eogymbhspbjf7.jpg',
      episodeOrder: 2,
      seasonId: 3,
    },
    {
      id: 15,
      name: 'É melhor não irritar E-3',
      url: 'https://do0od.com/e/mepscnbfxtjk',
      thumbnailUrl: 'https://img.doodcdn.co/snaps/46em8o2q8m4v4bu2.jpg',
      episodeOrder: 3,
      seasonId: 3,
    },
    {
      id: 16,
      name: 'O mago forte E-4',
      url: 'https://do0od.com/e/mtyay0h99va1',
      thumbnailUrl: 'https://img.doodcdn.co/snaps/qkzsxqm71x8ahxat.jpg',
      episodeOrder: 4,
      seasonId: 3,
    },
    {
      id: 17,
      name: 'O colega desprezado E-5',
      url: 'https://do0od.com/e/l53qgdcnwz9yskpolgxdmmk0bduzt5ov',
      thumbnailUrl: 'https://img.doodcdn.co/snaps/bj855bn2v5qmhihm.jpg',
      episodeOrder: 5,
      seasonId: 3,
    },
    {
      id: 18,
      name: 'O mago de ferro E-6',
      url: 'https://do0od.com/e/r18iflsbyqhj',
      thumbnailUrl: 'https://img.doodcdn.co/snaps/grzji5y8kd9idxbd.jpg',
      episodeOrder: 6,
      seasonId: 3,
    },
    {
      id: 19,
      name: 'Carta misteriosa E-6.5',
      url: 'https://do0od.com/e/ppzi57n7e3g6',
      thumbnailUrl: 'https://img.doodcdn.co/snaps/odvc2xvnnp4xyq8t.jpg',
      episodeOrder: 7,
      seasonId: 3,
    },
    {
      id: 20,
      name: 'Mago marionetista E-7',
      url: 'https://do0od.com/e/8b9orpoebej3',
      thumbnailUrl: 'https://img.doodcdn.co/snaps/yezy81me8xhpn7pi.jpg',
      episodeOrder: 8,
      seasonId: 3,
    },
    {
      id: 21,
      name: 'Magos lobos E-8',
      url: 'https://do0od.com/e/ra5nxdn9o4qr',
      thumbnailUrl: 'https://img.doodcdn.co/snaps/ymc4hmv45tt0lvwl.jpg',
      episodeOrder: 9,
      seasonId: 3,
    },
    {
      id: 22,
      name: 'Mago da aceleração E-9',
      url: 'https://do0od.com/e/36u36zi2h534',
      thumbnailUrl: 'https://img.doodcdn.co/snaps/x8umlmr0yur9rs9n.jpg',
      episodeOrder: 10,
      seasonId: 3,
    },
    {
      id: 23,
      name: 'Visionário divino E-10',
      url: 'https://do0od.com/e/fgmd4dqqnhlj',
      thumbnailUrl: 'https://img.doodcdn.co/snaps/c0e2zbaakjeebcqz.jpg',
      episodeOrder: 11,
      seasonId: 3,
    },
    {
      id: 24,
      name: 'Lei do mais forte E-11',
      url: 'https://do0od.com/e/9izc2kmpshem',
      thumbnailUrl: 'https://img.doodcdn.co/snaps/kzmt6anvtjnt7j1h.jpg',
      episodeOrder: 12,
      seasonId: 3,
    },
    {
      id: 25,
      name: 'O espelho mágico E-12',
      url: 'https://do0od.com/e/r3v4og3ehx4a',
      thumbnailUrl: 'https://img.doodcdn.co/snaps/nz0zaj25amy0prmj.jpg',
      episodeOrder: 13,
      seasonId: 3,
    },
    {
      id: 26,
      name: 'Os visionários E-13',
      url: 'https://do0od.com/e/y01rs4v3awlu',
      thumbnailUrl: 'https://img.doodcdn.co/snaps/a1ra2v0280k67km4.jpg',
      episodeOrder: 14,
      seasonId: 3,
    },
    {
      id: 27,
      name: 'A terra natal E-14',
      url: 'https://do0od.com/e/cig2npe5gvix',
      thumbnailUrl: 'https://img.doodcdn.co/snaps/8e9v8mpev4uk5fv2.jpg',
      episodeOrder: 15,
      seasonId: 3,
    },
    //Spy x Family
    {
      id: 28,
      name: 'Operação Strix E-1',
      url: 'https://do0od.com/e/g3oj50jxe5ju',
      thumbnailUrl: 'https://img.doodcdn.co/snaps/1xu8l8g4aee2rexp.jpg',
      episodeOrder: 1,
      seasonId: 5,
    },
    {
      id: 29,
      name: 'Garantir uma esposa E-2',
      url: 'https://do0od.com/e/buaxpyi7zo1c',
      thumbnailUrl: 'https://img.doodcdn.co/snaps/jpxu7bh4u83ut5hb.jpg',
      episodeOrder: 2,
      seasonId: 5,
    },
    {
      id: 30,
      name: 'Preparativos E-3',
      url: 'https://do0od.com/e/jxb9cxymxyjc',
      thumbnailUrl: 'https://img.doodcdn.co/snaps/y630kvyjk5aizpn7.jpg',
      episodeOrder: 3,
      seasonId: 5,
    },
    {
      id: 31,
      name: 'A entrevista E-4',
      url: 'https://do0od.com/e/gu4r9bz1g9iz',
      thumbnailUrl: 'https://img.doodcdn.co/snaps/71einn3dwlkxm5h1.jpg',
      episodeOrder: 4,
      seasonId: 5,
    },
    {
      id: 32,
      name: 'Aprovados ? E-5',
      url: 'https://do0od.com/e/yehmv4a4irh3',
      thumbnailUrl: 'https://img.doodcdn.co/snaps/8tvkiohuofo73n6u.jpg',
      episodeOrder: 5,
      seasonId: 5,
    },
    {
      id: 33,
      name: 'Esquema de amizade E-6',
      url: 'https://do0od.com/e/wa3zazqb6rhh',
      thumbnailUrl: 'https://img.doodcdn.co/snaps/mqw18l51voh6w6v2.jpg',
      episodeOrder: 6,
      seasonId: 5,
    },
    {
      id: 34,
      name: 'Segundo filho E-7',
      url: 'https://do0od.com/e/wa3zazqb6rhh',
      thumbnailUrl: 'https://img.doodcdn.co/snaps/f01j49rxvxkwqgjo.jpg',
      episodeOrder: 7,
      seasonId: 5,
    },
    {
      id: 35,
      name: 'Camuflagem E-8',
      url: 'https://do0od.com/e/ttjfqptxnufk',
      thumbnailUrl: 'https://img.doodcdn.co/snaps/ap7g982sekcu8qy5.jpg',
      episodeOrder: 8,
      seasonId: 5,
    },
    {
      id: 36,
      name: 'Ostente o seu amor E-9',
      url: 'https://do0od.com/e/jargh53ohio7',
      thumbnailUrl: 'https://img.doodcdn.co/snaps/x0ug8vr9d720uxoz.jpg',
      episodeOrder: 9,
      seasonId: 5,
    },
    {
      id: 37,
      name: 'O grande plano E-10',
      url: 'https://do0od.com/e/rzdc4wueac85',
      thumbnailUrl: 'https://img.doodcdn.co/snaps/3zxpkux0gncopa0z.jpg',
      episodeOrder: 10,
      seasonId: 5,
    },
    {
      id: 38,
      name: 'Estrela E-11',
      url: 'https://do0od.com/e/cmggkpn2hxkz',
      thumbnailUrl: 'https://img.doodcdn.co/snaps/woau9u7bw4u3nt28.jpg',
      episodeOrder: 11,
      seasonId: 5,
    },
    {
      id: 39,
      name: 'Parque dos pinguins E-12',
      url: 'https://do0od.com/e/gbhlctthl3ot',
      thumbnailUrl: 'https://img.doodcdn.co/snaps/gk7h287ptjjaqv5z.jpg',
      episodeOrder: 12,
      seasonId: 5,
    },
    //overlord
    {
      id: 40,
      name: 'Fim e começo E-1',
      url: 'https://do0od.com/e/cmsnkf9f4hok',
      thumbnailUrl: 'https://img.doodcdn.co/snaps/mwkos63pp8rsw8lo.jpg',
      episodeOrder: 1,
      seasonId: 6,
    },
    {
      id: 41,
      name: 'Guardiões E-2',
      url: 'https://do0od.com/e/cof7ecfn9wic',
      thumbnailUrl: 'https://img.doodcdn.co/snaps/eheky21vtcd63y9s.jpg',
      episodeOrder: 2,
      seasonId: 6,
    },
    {
      id: 42,
      name: 'Batalha na vila E-3',
      url: 'https://do0od.com/e/mtew35vvqihs',
      thumbnailUrl: 'https://img.doodcdn.co/snaps/i2l7qeke0l6ag10k.jpg',
      episodeOrder: 3,
      seasonId: 6,
    },
    {
      id: 43,
      name: 'Senhor da morte E-4',
      url: 'https://do0od.com/e/jqdjup44s8sp',
      thumbnailUrl: 'https://img.doodcdn.co/snaps/wet6wqmirhbt3g80.jpg',
      episodeOrder: 4,
      seasonId: 6,
    },
    {
      id: 44,
      name: 'Dois aventureiros E-5',
      url: 'https://do0od.com/e/bjjcqeexf6xe',
      thumbnailUrl: 'https://img.doodcdn.co/snaps/0zk9k9lnmyf0i81f.jpg',
      episodeOrder: 5,
      seasonId: 6,
    },
    {
      id: 45,
      name: 'Jornada E-6',
      url: 'https://do0od.com/e/56xqolkmbsmi',
      thumbnailUrl: 'https://img.doodcdn.co/snaps/teoxx904p3ftui4i.jpg',
      episodeOrder: 6,
      seasonId: 6,
    },
    {
      id: 46,
      name: 'Rei sábio E-7',
      url: 'https://do0od.com/e/c6ns2cqft4f0',
      thumbnailUrl: 'https://img.doodcdn.co/snaps/vkdv8i1uzi1fwa6q.jpg',
      episodeOrder: 7,
      seasonId: 6,
    },
    {
      id: 47,
      name: 'Espadas duplas E-8',
      url: 'https://do0od.com/e/fawclmn3b3ej',
      thumbnailUrl: 'https://img.doodcdn.co/snaps/r365my305fxj5m6q.jpg',
      episodeOrder: 8,
      seasonId: 6,
    },
    {
      id: 48,
      name: 'O cavaleiro negro E-9',
      url: 'https://do0od.com/e/kp84hd7sg7of',
      thumbnailUrl: 'https://img.doodcdn.co/snaps/dyfp399tmmxsp3ql.jpg',
      episodeOrder: 9,
      seasonId: 6,
    },
    {
      id: 49,
      name: 'Vampiro verdadeiro E-10',
      url: 'https://do0od.com/e/buxoe9frhuf5',
      thumbnailUrl: 'https://img.doodcdn.co/snaps/5qjsf39gnev6nxn0.jpg',
      episodeOrder: 10,
      seasonId: 6,
    },
    {
      id: 50,
      name: 'Confusão E-11',
      url: 'https://do0od.com/e/30j4g0wxhwjs',
      thumbnailUrl: 'https://img.doodcdn.co/snaps/1wql6okme39bk97o.jpg',
      episodeOrder: 11,
      seasonId: 6,
    },
    {
      id: 51,
      name: 'A valquíria E-12',
      url: 'https://do0od.com/e/tqairvb6vep8',
      thumbnailUrl: 'https://img.doodcdn.co/snaps/norxgoufeuqb44fx.jpg',
      episodeOrder: 12,
      seasonId: 6,
    },
    {
      id: 52,
      name: 'Jogador vs NPC E-13',
      url: 'https://do0od.com/e/8sv9eps6uclt',
      thumbnailUrl: 'https://img.doodcdn.co/snaps/rm1l15yquinctldp.jpg',
      episodeOrder: 13,
      seasonId: 6,
    },
    {
      id: 53,
      name: 'A alvorada E-1',
      url: 'https://do0od.com/e/xd07znxu395w',
      thumbnailUrl: 'https://img.doodcdn.co/snaps/mx4p0d39nbh87q5q.jpg',
      episodeOrder: 1,
      seasonId: 7,
    },
    {
      id: 54,
      name: 'Despedida E-2',
      url: 'https://do0od.com/e/mjw6nrcecz9s',
      thumbnailUrl: 'https://img.doodcdn.co/snaps/unowbbyw5ivoe5iv.jpg',
      episodeOrder: 2,
      seasonId: 7,
    },
    {
      id: 55,
      name: 'Lizardmen E-3',
      url: 'https://do0od.com/e/hkewzt35auas',
      thumbnailUrl: 'https://img.doodcdn.co/snaps/pp0hy3e6r2jxyqo8.jpg',
      episodeOrder: 3,
      seasonId: 7,
    },
    {
      id: 56,
      name: 'Exército da morte E-4',
      url: 'https://do0od.com/e/e9fgf0p25nb3',
      thumbnailUrl: 'https://img.doodcdn.co/snaps/0gbbii6ljq8zra06.jpg',
      episodeOrder: 4,
      seasonId: 7,
    },
    {
      id: 57,
      name: 'O deus congelante E-5',
      url: 'https://do0od.com/e/v7e88ptt35ow',
      thumbnailUrl: 'https://img.doodcdn.co/snaps/wtv2cjb18gkomdu9.jpg',
      episodeOrder: 5,
      seasonId: 7,
    },
    {
      id: 58,
      name: 'Os que auxiliam E-6',
      url: 'https://do0od.com/e/8l4w8gi7wpm4',
      thumbnailUrl: 'https://img.doodcdn.co/snaps/mfrxn0jtgywoe0eg.jpg',
      episodeOrder: 6,
      seasonId: 7,
    },
    {
      id: 59,
      name: 'Rosas Azuis E-7',
      url: 'https://do0od.com/e/vbrrwrqoy3i1',
      thumbnailUrl: 'https://img.doodcdn.co/snaps/46gt947gqs3h7x2p.jpg',
      episodeOrder: 7,
      seasonId: 7,
    },
    {
      id: 60,
      name: 'O sentimento E-8',
      url: 'https://do0od.com/e/w13roh5mk1sw',
      thumbnailUrl: 'https://img.doodcdn.co/snaps/71kkzd1xbvssk97j.jpg',
      episodeOrder: 8,
      seasonId: 7,
    },
    {
      id: 61,
      name: 'Faíscas E-9',
      url: 'https://do0od.com/e/i9dhdy9h4loo',
      thumbnailUrl: 'https://img.doodcdn.co/snaps/v13gegq8bqwhxtqd.jpg',
      episodeOrder: 9,
      seasonId: 7,
    },
    {
      id: 62,
      name: 'Distúrbios E-10',
      url: 'https://do0od.com/e/gk3sxqle11o2',
      thumbnailUrl: 'https://img.doodcdn.co/snaps/acx0dm1flp6xgtxr.jpg',
      episodeOrder: 10,
      seasonId: 7,
    },
    {
      id: 63,
      name: 'Jaldabaoth E-11',
      url: 'https://do0od.com/e/kvwjxnls29at',
      thumbnailUrl: 'https://img.doodcdn.co/snaps/epijn4tqfz0jiw04.jpg',
      episodeOrder: 11,
      seasonId: 7,
    },
    {
      id: 64,
      name: 'A batalha final E-12',
      url: 'https://do0od.com/e/pthrk8xgi4j1',
      thumbnailUrl: 'https://img.doodcdn.co/snaps/luyjv7hsrhlnpx50.jpg',
      episodeOrder: 12,
      seasonId: 7,
    },
    {
      id: 65,
      name: 'O trunfo final E-13',
      url: 'https://do0od.com/e/gth9280tjyz8',
      thumbnailUrl: 'https://img.doodcdn.co/snaps/xhuw3cgxgptc04dl.jpg',
      episodeOrder: 13,
      seasonId: 7,
    },
    //Jujutsu
    {
      id: 66,
      name: 'Ryomen sukuna E-1',
      url: 'https://do0od.com/e/bbgbnop08rr4',
      thumbnailUrl: 'https://img.doodcdn.co/snaps/v262sze0wqtaogkm.jpg',
      episodeOrder: 1,
      seasonId: 1,
    },
    {
      id: 67,
      name: 'Por mim mesmo E-2',
      url: 'https://do0od.com/e/tur015yan50j',
      thumbnailUrl: 'https://img.doodcdn.co/snaps/mr15ywnxybaru6gs.jpg',
      episodeOrder: 2,
      seasonId: 1,
    },
    {
      id: 68,
      name: 'Garota de aço E-3',
      url: 'https://do0od.com/e/iph8c0jkw104',
      thumbnailUrl: 'https://img.doodcdn.co/snaps/iz3gjtc8eaecpg5k.jpg',
      episodeOrder: 3,
      seasonId: 1,
    },
    {
      id: 69,
      name: 'Morte ao feto E-4',
      url: 'https://do0od.com/e/vqjnm4c63jkm',
      thumbnailUrl: 'https://img.doodcdn.co/snaps/hz2d4vi3ngb6kgap.jpg',
      episodeOrder: 4,
      seasonId: 1,
    },
    {
      id: 70,
      name: 'Amaldiçoado E-5',
      url: 'https://do0od.com/e/4wnpetd3jgcp',
      thumbnailUrl: 'https://img.doodcdn.co/snaps/vkbgxdwtcl59qily.jpg',
      episodeOrder: 5,
      seasonId: 1,
    },
    {
      id: 71,
      name: 'Depois da chuva E-6',
      url: 'https://do0od.com/e/hgbx3gqvix4c',
      thumbnailUrl: 'https://img.doodcdn.co/snaps/q11k3dwqwg1623xa.jpg',
      episodeOrder: 6,
      seasonId: 1,
    },
    {
      id: 72,
      name: 'Ataque E-7',
      url: 'https://do0od.com/e/o3cz5t8naoep',
      thumbnailUrl: 'https://img.doodcdn.co/snaps/ipo89mbvvv1h6249.jpg',
      episodeOrder: 7,
      seasonId: 1,
    },
    {
      id: 73,
      name: 'Tédio E-8',
      url: 'https://do0od.com/e/jrg79j4luqhq',
      thumbnailUrl: 'https://img.doodcdn.co/snaps/xf40f0sqwq3r5jyd.jpg',
      episodeOrder: 8,
      seasonId: 1,
    },
    {
      id: 74,
      name: 'Peixes pequenos E-9',
      url: 'https://do0od.com/e/ar2mdprzogw2',
      thumbnailUrl: 'https://img.doodcdn.co/snaps/sovibltftd47qzsv.jpg',
      episodeOrder: 9,
      seasonId: 1,
    },
    {
      id: 75,
      name: 'Transfiguração E-10',
      url: 'https://do0od.com/e/6h9z2kwjx282',
      thumbnailUrl: 'https://img.doodcdn.co/snaps/5vu8f5suhzj0w1ut.jpg',
      episodeOrder: 10,
      seasonId: 1,
    },
    {
      id: 76,
      name: 'Mente fechada E-11',
      url: 'https://do0od.com/e/kj5dyl1a4whe',
      thumbnailUrl: 'https://img.doodcdn.co/snaps/r5i99y4o52jio5lb.jpg',
      episodeOrder: 11,
      seasonId: 1,
    },
    {
      id: 77,
      name: 'Para você E-12',
      url: 'https://do0od.com/e/n80h80kpugoz',
      thumbnailUrl: 'https://img.doodcdn.co/snaps/n81fo05zec9jlwjx.jpg',
      episodeOrder: 12,
      seasonId: 1,
    },
    {
      id: 78,
      name: 'Amanhã E-13',
      url: 'https://do0od.com/e/cwx37dpgeopo',
      thumbnailUrl: 'https://img.doodcdn.co/snaps/1jrflid7qny3dphf.jpg',
      episodeOrder: 13,
      seasonId: 1,
    },
    {
      id: 79,
      name: 'Intercâmbio 0 E-14',
      url: 'https://do0od.com/e/1xqbziuv7h70',
      thumbnailUrl: 'https://img.doodcdn.co/snaps/397wi602jlbc6j48.jpg',
      episodeOrder: 14,
      seasonId: 1,
    },
    {
      id: 80,
      name: 'Intercâmbio 1 E-15',
      url: 'https://do0od.com/e/j70lroewijc2',
      thumbnailUrl: 'https://img.doodcdn.co/snaps/krkrej40viibqdzx.jpg',
      episodeOrder: 15,
      seasonId: 1,
    },
    {
      id: 81,
      name: 'Intercâmbio 2 E-16',
      url: 'https://do0od.com/e/jrrepajwktru',
      thumbnailUrl: 'https://img.doodcdn.co/snaps/zwkkmrvbkpz4x4sh.jpg',
      episodeOrder: 16,
      seasonId: 1,
    },
    {
      id: 82,
      name: 'Intercâmbio 3 E-17',
      url: 'https://do0od.com/e/lwdolcfyquwc',
      thumbnailUrl: 'https://img.doodcdn.co/snaps/la53dnfl70p6p3yw.jpg',
      episodeOrder: 17,
      seasonId: 1,
    },
    {
      id: 83,
      name: 'Sábio E-18',
      url: 'https://do0od.com/e/bq9tjvs1pixb',
      thumbnailUrl: 'https://img.doodcdn.co/snaps/7uhvlyvtbz20jkxf.jpg',
      episodeOrder: 18,
      seasonId: 1,
    },
    {
      id: 84,
      name: 'Fulgor negro E-19',
      url: 'https://do0od.com/e/7vwl50nurwux',
      thumbnailUrl: 'https://img.doodcdn.co/snaps/hjb30deuo78ty8ct.jpg',
      episodeOrder: 19,
      seasonId: 1,
    },
    {
      id: 85,
      name: 'Fora do padrão E-20',
      url: 'https://do0od.com/e/9celqs8acell',
      thumbnailUrl: 'https://img.doodcdn.co/snaps/cj0zc41qsp4zsdwh.jpg',
      episodeOrder: 20,
      seasonId: 1,
    },
    {
      id: 86,
      name: 'Jujutsu koshien E-21',
      url: 'https://do0od.com/e/1g8h3n4gpiyn',
      thumbnailUrl: 'https://img.doodcdn.co/snaps/udujypm8mal6bq77.jpg',
      episodeOrder: 21,
      seasonId: 1,
    },
    {
      id: 87,
      name: 'A origem 1 E-22',
      url: 'https://do0od.com/e/zj6x6nwasbbo',
      thumbnailUrl: 'https://img.doodcdn.co/snaps/koa6qjz1n9t8i9s7.jpg',
      episodeOrder: 22,
      seasonId: 1,
    },
    {
      id: 88,
      name: 'A origem 2 E-23',
      url: 'https://do0od.com/e/yn8acoc3zlfs',
      thumbnailUrl: 'https://img.doodcdn.co/snaps/chbe77zpckgnazuj.jpg',
      episodeOrder: 23,
      seasonId: 1,
    },
    {
      id: 89,
      name: 'Cúmplices E-24',
      url: 'https://do0od.com/e/1iresidzf93v',
      thumbnailUrl: 'https://img.doodcdn.co/snaps/o8fr2o4g8dzkbqw8.jpg',
      episodeOrder: 24,
      seasonId: 1,
    },
    {
      id: 90,
      name: 'Inventário E-1',
      url: 'https://do0od.com/e/2t3b30riuhl7',
      thumbnailUrl: 'https://img.doodcdn.co/snaps/ix8cwzd34n7pdf8s.jpg',
      episodeOrder: 1,
      seasonId: 2,
    },
    {
      id: 91,
      name: 'Inventário 2 E-2',
      url: 'https://do0od.com/e/l31a1k6nzow0',
      thumbnailUrl: 'https://img.doodcdn.co/snaps/mmg9z0pk0dc8ubm4.jpg',
      episodeOrder: 2,
      seasonId: 2,
    },
    {
      id: 92,
      name: 'Inventário 3 E-3',
      url: 'https://do0od.com/e/5blymeibuo0y',
      thumbnailUrl: 'https://img.doodcdn.co/snaps/cum1d11pu00am3x0.jpg',
      episodeOrder: 3,
      seasonId: 2,
    },
    {
      id: 93,
      name: 'Inventário 4 E-4',
      url: 'https://do0od.com/e/2nf9crsvt181',
      thumbnailUrl: 'https://img.doodcdn.co/snaps/3n3ax51eh7cjp0xh.jpg',
      episodeOrder: 4,
      seasonId: 2,
    },
    {
      id: 94,
      name: 'Morte prematura E-5',
      url: 'https://do0od.com/e/qq8zsxtwir48',
      thumbnailUrl: 'https://img.doodcdn.co/snaps/fsv6vwqahgp9i3db.jpg',
      episodeOrder: 5,
      seasonId: 2,
    },
    {
      id: 95,
      name: 'E é assim E-6',
      url: 'https://do0od.com/e/f23srzqevreg',
      thumbnailUrl: 'https://img.doodcdn.co/snaps/tzmbruxi4hbfk6yg.jpg',
      episodeOrder: 6,
      seasonId: 2,
    },
    {
      id: 96,
      name: 'Festival ao fim E-7',
      url: 'https://do0od.com/e/1ifg8yfgkpej',
      thumbnailUrl: 'https://img.doodcdn.co/snaps/so2ejo6sebydlhrn.jpg',
      episodeOrder: 7,
      seasonId: 2,
    },
    {
      id: 97,
      name: 'Incidente E-8',
      url: 'https://do0od.com/e/ilr9uvb0yfjo',
      thumbnailUrl: 'https://img.doodcdn.co/snaps/qd6ybsbsurgv1amb.jpg',
      episodeOrder: 8,
      seasonId: 2,
    },
    {
      id: 98,
      name: 'Incidente 2 E-9',
      url: 'https://do0od.com/e/bwzqgv0wc1iy',
      thumbnailUrl: 'https://img.doodcdn.co/snaps/vjnerx7yhykqvf4q.jpg',
      episodeOrder: 9,
      seasonId: 2,
    },
    {
      id: 99,
      name: 'Pandemônio E-10',
      url: 'https://do0od.com/e/vw7eocidi4av',
      thumbnailUrl: 'https://img.doodcdn.co/snaps/tqx7nmzs29tarn2m.jpg',
      episodeOrder: 10,
      seasonId: 2,
    },
    {
      id: 100,
      name: 'Sessão E-11',
      url: 'https://do0od.com/e/vgyq5qosedxh',
      thumbnailUrl: 'https://img.doodcdn.co/snaps/7navbg3f0jwrsgfv.jpg',
      episodeOrder: 11,
      seasonId: 2,
    },
    {
      id: 101,
      name: 'Faca cega E-12',
      url: 'https://do0od.com/e/ozxjsiqul54j',
      thumbnailUrl: 'https://img.doodcdn.co/snaps/m2jn7wlndim2zb73.jpg',
      episodeOrder: 12,
      seasonId: 2,
    },
    {
      id: 102,
      name: 'Escama E-13',
      url: 'https://do0od.com/e/vc8q6xaxxq4y',
      thumbnailUrl: 'https://img.doodcdn.co/snaps/zuplqvly7fgqjejl.jpg',
      episodeOrder: 13,
      seasonId: 2,
    },
    {
      id: 103,
      name: 'Flutuações E-14',
      url: 'https://do0od.com/e/2ri1791a6roh',
      thumbnailUrl: 'https://img.doodcdn.co/snaps/nzrs7jeqxpzufdpq.jpg',
      episodeOrder: 14,
      seasonId: 2,
    },
    {
      id: 104,
      name: 'Flutuações 2 E-15',
      url: 'https://do0od.com/e/ti9pgbbo46xj',
      thumbnailUrl: 'https://img.doodcdn.co/snaps/ecckt2pwj3dvpsrg.jpg',
      episodeOrder: 15,
      seasonId: 2,
    },
    {
      id: 105,
      name: 'Trovão E-16',
      url: 'https://do0od.com/e/ri421rt3n034',
      thumbnailUrl: 'https://img.doodcdn.co/snaps/ro9alm2j3bhpufph.jpg',
      episodeOrder: 16,
      seasonId: 2,
    },
    {
      id: 106,
      name: 'Trovão 2 E-17',
      url: 'https://do0od.com/e/o6stm0minc0q',
      thumbnailUrl: 'https://img.doodcdn.co/snaps/2b45kvuhglfktgk5.jpg',
      episodeOrder: 17,
      seasonId: 2,
    },
    {
      id: 107,
      name: 'Certo e errado E-18',
      url: 'https://do0od.com/e/3qoi56wa8g90',
      thumbnailUrl: 'https://img.doodcdn.co/snaps/0ioyqs6wnxskwlf1.jpg',
      episodeOrder: 18,
      seasonId: 2,
    },
    {
      id: 108,
      name: 'Certo e errado 2 E-19',
      url: 'https://do0od.com/e/spgo928ntd28',
      thumbnailUrl: 'https://img.doodcdn.co/snaps/viy470zsverfu9vj.jpg',
      episodeOrder: 19,
      seasonId: 2,
    },
    {
      id: 109,
      name: 'Certo e errado 3 E-20',
      url: 'https://do0od.com/e/1v0q15oa8x6l',
      thumbnailUrl: 'https://img.doodcdn.co/snaps/zosvvfti1264zzvz.jpg',
      episodeOrder: 20,
      seasonId: 2,
    },
    {
      id: 110,
      name: 'Metamorfose E-21',
      url: 'https://do0od.com/e/t3h1rkiid75o',
      thumbnailUrl: 'https://img.doodcdn.co/snaps/nocn3ihhlvk08qtd.jpg',
      episodeOrder: 21,
      seasonId: 2,
    },
    {
      id: 111,
      name: 'Metamorfose 2 E-22',
      url: 'https://do0od.com/e/t7mwg8ss0zvh',
      thumbnailUrl: 'https://img.doodcdn.co/snaps/r9kd61yws9oaw6k1.jpg',
      episodeOrder: 22,
      seasonId: 2,
    },
    {
      id: 112,
      name: 'Portões fechado E-23',
      url: 'https://do0od.com/e/824h79zkihmy',
      thumbnailUrl: 'https://img.doodcdn.co/snaps/1i7cailuaytwfkdg.jpg',
      episodeOrder: 23,
      seasonId: 2,
    },
    {
      id: 113,
      name: 'Cachorro e Moto E-1',
      url: 'https://do0od.com/e/tslwc42nizbj',
      thumbnailUrl: 'https://img.doodcdn.co/snaps/xifci247agajsccb.jpg',
      episodeOrder: 1,
      seasonId: 9,
    },
    {
      id: 114,
      name: 'Chegada em Tokyo E-2',
      url: 'https://do0od.com/e/bzjtui5whoyk',
      thumbnailUrl: 'https://img.doodcdn.co/snaps/gei9xa83uqakzeil.jpg',
      episodeOrder: 2,
      seasonId: 9,
    },
    {
      id: 115,
      name: 'O paradeiro E-3',
      url: 'https://do0od.com/e/07jdf1swaae9',
      thumbnailUrl: 'https://img.doodcdn.co/snaps/ndh2stl47wp5xbux.jpg',
      episodeOrder: 3,
      seasonId: 9,
    },
    {
      id: 116,
      name: 'Resgate E-4',
      url: 'https://do0od.com/e/ymh4ibcvuorw',
      thumbnailUrl: 'https://img.doodcdn.co/snaps/dth1j7idl488qvik.jpg',
      episodeOrder: 4,
      seasonId: 9,
    },
    {
      id: 117,
      name: 'O demônio da arma E-5',
      url: 'https://do0od.com/e/0mxxo68hg6m7',
      thumbnailUrl: 'https://img.doodcdn.co/snaps/6ytd2hd4b97qywok.jpg',
      episodeOrder: 5,
      seasonId: 9,
    },
    {
      id: 118,
      name: 'Matem o Denji E-6',
      url: 'https://do0od.com/e/mi11lyp3fxeb',
      thumbnailUrl: 'https://img.doodcdn.co/snaps/u9we6hu93pz87ybe.jpg',
      episodeOrder: 6,
      seasonId: 9,
    },
    {
      id: 119,
      name: 'O sabor do beijo E-7',
      url: 'https://do0od.com/e/qc4rbglsn2nk',
      thumbnailUrl: 'https://img.doodcdn.co/snaps/p1mhlhdwn4sfe0i4.jpg',
      episodeOrder: 7,
      seasonId: 9,
    },
    {
      id: 120,
      name: 'O som do disparo E-8',
      url: 'https://do0od.com/e/oatx0t0qft2e',
      thumbnailUrl: 'https://img.doodcdn.co/snaps/dhf15vwlmikxao4p.jpg',
      episodeOrder: 8,
      seasonId: 9,
    },
    {
      id: 121,
      name: 'De Kyoto E-9',
      url: 'https://do0od.com/e/nr6uw9eai1fv',
      thumbnailUrl: 'https://img.doodcdn.co/snaps/vov03r34y5xe7psv.jpg',
      episodeOrder: 9,
      seasonId: 9,
    },
    {
      id: 122,
      name: 'Ainda mais pobre E-10',
      url: 'https://do0od.com/e/otoxh5vkvur4',
      thumbnailUrl: 'https://img.doodcdn.co/snaps/be3909bac9sveg6g.jpg',
      episodeOrder: 10,
      seasonId: 9,
    },
    {
      id: 123,
      name: 'Início do plano E-11',
      url: 'https://do0od.com/e/9xt5s9jz7b5v',
      thumbnailUrl: 'https://img.doodcdn.co/snaps/1y78rb4m7t8tkcz2.jpg',
      episodeOrder: 11,
      seasonId: 9,
    },
    {
      id: 124,
      name: 'Katana vs Moto E-12',
      url: 'https://do0od.com/e/lif88ftcpw2q',
      thumbnailUrl: 'https://img.doodcdn.co/snaps/y4q2hbsqia28schn.jpg',
      episodeOrder: 12,
      seasonId: 9,
    },
    {
      id: 125,
      name: 'One Piece Film: Strong World',
      url: 'https://do0od.com/e/01xim6rqcuwh8xvai24cgz7e9ytjo1a1',
      thumbnailUrl: 'https://img.doodcdn.co/snaps/qk3vhak7yboq6y5n.jpg',
      episodeOrder: 1,
      seasonId: 10,
    },
  ];

  for (const episodesData of episodesToCreate) {
    const existingSeason = await prisma.seasons.findUnique({
      where: { id: episodesData.seasonId },
    });

    const existingEpisodes = await prisma.episodes.findUnique({
      where: { id: episodesData.id },
    });

    if (existingSeason) {
      if (!existingEpisodes) {
        await prisma.episodes.create({
          data: {
            name: episodesData.name,
            url: episodesData.url,
            thumbnailUrl: episodesData.thumbnailUrl,
            episodeOrder: episodesData.episodeOrder,
            seasons: {
              connect: {
                id: episodesData.seasonId,
              },
            },
          },
        });
      }
    }
  }
}

createEpisodes()
  .then(() => {
    console.log('Episódios gerados com sucesso.');
  })
  .catch((error) => {
    console.error('Erro ao gerar os episódios:', error);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
